name: tether_pet_owner
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  custom_clippers: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/Sora-Bold.ttf
        - asset: assets/fonts/Sora/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora/Sora-Light.ttf
        - asset: assets/fonts/Sora/Sora-Medium.ttf
        - asset: assets/fonts/Sora/Sora-Regular.ttf
        - asset: assets/fonts/Sora/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora/Sora-Thin.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf

flutter_gen:
  output: lib/src/assets
  line_length: 80

  integrations:
    flutter_svg: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/primary_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
